"""Thumbnail cache cleaner plugin.

Cleans thumbnail cache generated by file managers and image viewers on Linux.
"""
from pathlib import Path
from typing import TYPE_CHECKING, Any

from .base import BasePlugin

if TYPE_CHECKING:
    from ..managers.cleaner_manager import CleanableItem, SafetyLevel  # noqa: F401


class ThumbnailCacheCleaner(BasePlugin):
    """Cleans thumbnail cache from ~/.cache/thumbnails."""

    def __init__(self, home_dir: Path = Path.home(), cache_dir: Path | None = None):
        self.home_dir = Path(home_dir)
        self.thumbnails_dir = Path(cache_dir) if cache_dir is not None else self.home_dir / ".cache" / "thumbnails"

    def get_name(self) -> str:
        return "Thumbnail Cache"

    def get_description(self) -> str:
        return "Cached thumbnail images generated by file managers and image viewers."

    def scan(self) -> "list[CleanableItem]":
        items: list = []

        if not self.thumbnails_dir.exists():
            return items

        # Scan all subdirectories (normal, large, fail, etc.) and files in the
        # top-level thumbnails directory itself (some systems store files directly).
        try:
            for subdir in self.thumbnails_dir.iterdir():
                if subdir.is_dir():
                    items.extend(self._scan_thumbnail_dir(subdir))
                elif subdir.is_file():
                    # Include files directly under thumbnails_dir
                    from ..managers.cleaner_manager import CleanableItem, SafetyLevel

                    try:
                        size = subdir.stat().st_size
                        items.append(
                            CleanableItem(
                                path=str(subdir),
                                size=size,
                                description=f"Thumbnail: {subdir.name}",
                                safety=SafetyLevel.SAFE,
                            )
                        )
                    except (OSError, PermissionError):
                        continue
        except (OSError, PermissionError):
            # Can't access thumbnails directory
            pass

        return items

    def _scan_thumbnail_dir(self, path: Path) -> "list[CleanableItem]":
        """Scan a thumbnail subdirectory."""
        items: list = []

        try:
            for entry in path.iterdir():
                if entry.is_file():
                    try:
                        size = entry.stat().st_size
                        category = path.name.title()  # 'normal' -> 'Normal', 'large' -> 'Large'
                        from ..managers.cleaner_manager import CleanableItem, SafetyLevel

                        items.append(
                            CleanableItem(
                                path=str(entry),
                                size=size,
                                description=f"{category} thumbnail: {entry.name}",
                                safety=SafetyLevel.SAFE,
                            )
                        )
                    except (OSError, PermissionError):
                        # Skip files we can't access
                        continue
        except (OSError, PermissionError):
            # Skip directories we can't access
            pass

        return items

    def clean(self, items: "list[CleanableItem]") -> dict[str, Any]:
        result: dict[str, Any] = {"success": True, "cleaned_count": 0, "total_size": 0, "errors": []}

        for item in items:
            try:
                file_path = Path(item.path)
                if file_path.exists():
                    size = file_path.stat().st_size
                    file_path.unlink()
                    result["cleaned_count"] += 1
                    result["total_size"] += size
            except (OSError, PermissionError) as e:
                result["errors"].append(f"Failed to delete {item.path}: {e}")
                result["success"] = False

        return result

    def is_available(self) -> bool:
        """Thumbnails cleaning is available if the thumbnails directory exists."""
        return self.thumbnails_dir.exists()

    def supports_dry_run(self) -> bool:
        return True

    def clean_dry_run(self, items: "list[CleanableItem]") -> dict[str, Any]:
        return {
            "success": True,
            "cleaned_count": len(items),
            "total_size": sum(item.size for item in items),
            "errors": [],
            "dry_run": True,
        }

    def get_priority(self) -> int:
        """Medium-high priority for thumbnails."""
        return 40
